// components/Nav.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useLang } from '@/contexts/LangContext'
import type { Locale } from '@/lib/i18n'

export default function Nav() {
  const { t, locale, setLocale } = useLang()
  const [menuOpen, setMenuOpen] = useState(false)

  const navLinks = [
    { key: 'nav.home', href: '/' },
    { key: 'nav.about', href: '/#about' },
    { key: 'nav.services', href: '/#service' },
    { key: 'nav.faq', href: '/#faq' },
    { key: 'nav.contact', href: '/#contact' },
  ] as const

  const langOptions: { code: Locale; label: string }[] = [
    { code: 'zh', label: '简' },
    { code: 'tc', label: '繁' },
    { code: 'en', label: 'EN' },
  ]

  return (
    <div className="fixed top-0 left-0 w-full z-50">
      {/* Topbar */}
      <div className="bg-darkgreen">
        <div className="max-w-6xl mx-auto px-4 flex items-center justify-between py-1.5">
          <div className="flex items-center gap-3 flex-wrap">
            <span className="text-white text-sm">徐培康</span>
            <img src="/img/phone2.svg" alt="phone" className="w-5 h-5" />
            <a
              href="tel:+14167223453"
              className="text-white text-sm hover:text-lightgreen transition-colors"
              onClick={() => {
                if (typeof window !== 'undefined' && (window as any).gtag_report_conversion) {
                  ;(window as any).gtag_report_conversion('tel:416-722-3453')
                }
              }}
            >
              416-722-3453
            </a>
            <Link
              href="/price"
              className="hidden sm:inline-block text-white text-sm border border-white rounded-full px-3 py-0.5 ml-2 hover:bg-white hover:text-darkgreen transition-all duration-300"
            >
              {t('nav.price-list')}
            </Link>
            <a
              href="/img/docs/BAO-consumer-info-april-2021.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="hidden md:inline-block text-white text-sm border border-white rounded-full px-3 py-0.5 hover:bg-white hover:text-darkgreen transition-all duration-300"
            >
              {t('nav.guide')}
            </a>
          </div>
          <div className="flex items-center gap-1">
            {langOptions.map((opt) => (
              <button
                key={opt.code}
                onClick={() => setLocale(opt.code)}
                className={`text-sm px-2 py-0.5 rounded transition-colors ${
                  locale === opt.code
                    ? 'text-white font-bold underline'
                    : 'text-lightgreen hover:text-white'
                }`}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Main Navbar */}
      <nav className="bg-lightgrey shadow-md">
        <div className="max-w-6xl mx-auto px-4 flex items-center justify-between h-14">
          <Link
            href="/"
            className="font-cinzel font-bold text-xl md:text-2xl text-green hover:text-green"
          >
            {t('nav.name')}
          </Link>

          {/* Desktop nav */}
          <ul className="hidden lg:flex items-center gap-1">
            {navLinks.map((link) => (
              <li key={link.key}>
                <Link
                  href={link.href}
                  className="text-green text-base px-3 py-2 hover:text-darkgreen transition-colors block"
                >
                  {t(link.key)}
                </Link>
              </li>
            ))}
            <li>
              <Link
                href="/price"
                className="text-green text-base px-3 py-2 hover:text-darkgreen transition-colors block"
              >
                {t('nav.price-list')}
              </Link>
            </li>
          </ul>

          {/* Mobile hamburger */}
          <button
            onClick={() => setMenuOpen(!menuOpen)}
            className="lg:hidden bg-green text-white p-2 rounded focus:outline-none"
            aria-label="Toggle menu"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              {menuOpen ? (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="lg:hidden bg-lightgrey border-t border-lightgreen">
            <ul className="flex flex-col py-2">
              {navLinks.map((link) => (
                <li key={link.key}>
                  <Link
                    href={link.href}
                    onClick={() => setMenuOpen(false)}
                    className="text-green text-base px-6 py-3 hover:text-darkgreen hover:bg-lightgreen transition-colors block"
                  >
                    {t(link.key)}
                  </Link>
                </li>
              ))}
              <li>
                <Link
                  href="/price"
                  onClick={() => setMenuOpen(false)}
                  className="text-green text-base px-6 py-3 hover:text-darkgreen hover:bg-lightgreen transition-colors block"
                >
                  {t('nav.price-list')}
                </Link>
              </li>
              <li>
                <a
                  href="/img/docs/BAO-consumer-info-april-2021.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-green text-base px-6 py-3 hover:text-darkgreen hover:bg-lightgreen transition-colors block"
                >
                  {t('nav.guide')}
                </a>
              </li>
            </ul>
          </div>
        )}
      </nav>
    </div>
  )
}

// components/Nav.vue
<i18n>
{
  "en":{
    "name":"Pre-Plan Cemetery & Funeral",
      "about":"About Us",
      "cf":"Our Services",
      "faq":"FAQ",
      "area":"Service Area",
      "contact":"Contact Us"
  },
  "zh":{
    "name":"多伦多预置墓园及殡葬服务",
    "home":"首页",
    "price-list":"预置墓园 & 殡葬服务价目表",
    "guide":"安省后事处理指南",
    "about":"关于我们",
    "cf":"我们的服务",
    "faq":"常见问题",
    "area":"服务地区",
    "contact":"联系我们"
      },
  "tc":{
    "name":"多倫多預置墓園及殯葬服務",
    "home":"首頁",
    "price-list":"預置墓園 & 殯葬服務价目表",
    "guide":"安省後事處理指南",
    "about":"關於我們",
    "cf":"我們的服務",
       "faq":"常見問題",
       "area":"服務地區",
       "contact":"聯絡我們"
  }
}
</i18n>
<template>
  <div style="position: fixed; width: 100%; z-index: 999">
    <div class="topbar">
      <b-navbar toggleable="lg" type="dark" variant="nav">
        <b-navbar-nav class="topbar-inner">
          <!-- <b-nav-item :href="switchLocalePath('en')">En</b-nav-item> -->
          <div class="topbar-info-wrap">
            <span>徐培康</span>
            <img src="/img/phone2.svg" alt="" />
            <a
              onclick="return gtag_report_conversion('tel:416-722-3453')"
              href="tel:+14167223453"
              >416-722-3453</a
            >
            <nuxt-link :to="localePath('price')" class="price-list-link">{{
              $t("price-list")
            }}</nuxt-link>
            <a
              href="/img/docs/BAO-consumer-info-april-2021.pdf"
              target="_blank"
              class="price-list-link"
              >{{ $t("guide") }}</a
            >
          </div>
          <div>
            <b-nav-item :href="switchLocalePath('zh')">简</b-nav-item>
            <b-nav-item :href="switchLocalePath('tc')">繁</b-nav-item>
          </div>
        </b-navbar-nav>
      </b-navbar>
    </div>
    <b-navbar toggleable="lg" type="dark" variant="nav">
      <b-navbar-brand> {{ $t("name") }}</b-navbar-brand>
      <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
      <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav class="ml-auto">
          <b-nav-item>
            <nuxt-link :to="localePath('index')">{{ $t("home") }}</nuxt-link>
          </b-nav-item>
          <b-nav-item>
            <nuxt-link :to="{ path: localePath('index'), hash: '#about' }">{{
              $t("about")
            }}</nuxt-link>
          </b-nav-item>
          <b-nav-item>
            <nuxt-link :to="{ path: localePath('index'), hash: '#service' }">{{
              $t("cf")
            }}</nuxt-link>
          </b-nav-item>
          <b-nav-item>
            <nuxt-link :to="{ path: localePath('index'), hash: '#faq' }">{{
              $t("faq")
            }}</nuxt-link>
          </b-nav-item>
          <b-nav-item>
            <nuxt-link
              :to="{ path: localePath('index'), hash: '#servicearea' }"
              >{{ $t("area") }}</nuxt-link
            >
          </b-nav-item>
          <b-nav-item>
            <nuxt-link :to="{ path: localePath('index'), hash: '#contact' }">{{
              $t("contact")
            }}</nuxt-link>
          </b-nav-item>
          <b-nav-item class="display-sm">
            <nuxt-link :to="localePath('price')">{{
              $t("price-list")
            }}</nuxt-link>
          </b-nav-item>
          <b-nav-item
            class="display-sm"
            href="/img/docs/BAO-consumer-info-april-2021.pdf"
            target="_blank"
          >
            <a
              href="/img/docs/BAO-consumer-info-april-2021.pdf"
              target="_blank"
              >{{ $t("guide") }}</a
            >
          </b-nav-item>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>
  </div>
</template>

<script>
export default {
  methods: {
    scrollMeTo(refName) {
      var element = this.$refs[refName];
      var top = element.offsetTop;

      window.scrollTo(0, top);
    }
  }
};
</script>

<style lang="scss">
@import "~/assets/css/main.scss";

.nav-item {
  a {
    color: $green;
  }
}
</style>
<style lang="scss" scoped>
@import "~/assets/css/main.scss";

.price-list-link {
  padding: 5px 10px;
  border-radius: 15px;
  border: 1px solid #fff;
  transition: all 0.4s ease;
  &:hover {
    background-color: #fff;
    color: $green;
  }
}
.display-sm {
  display: none;
}
@media all and (max-width: 768px) {
  .price-list-link {
    display: none;
  }
  .display-sm {
    display: block;
  }
}
</style>
